api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Nginx server"
  homepage = "https://github.com/initializ-buildpacks/nginx"
  id = "initializ-buildpacks/nginx"
  keywords = ["nginx", "server", "distribution"]
  name = "Initializ Buildpack for Nginx Server"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/configure", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.25.*"



  [[metadata.dependency-constraints]]
    constraint = "1.25.*"
    id = "nginx"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.26.*"
    id = "nginx"
    patches = 2
  [metadata.version-lines]
    mainline = "1.25.*"
    stable = "1.26.*"

[[stacks]]
  id = "Initializ Distroless Stack"
