api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate Nginx server"
  homepage = "https://github.com/initializ-buildpacks/nginx"
  id = "initializ-buildpacks/nginx"
  keywords = ["nginx", "server", "distribution"]
  name = "Initializ Buildpack for Nginx Server"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "bin/configure", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    nginx = "1.26.*"

  [[metadata.dependencies]]
    checksum = "sha256:12775fe60e83b5a3a93b124654ea176f21bf750190d45641317ff2b48637bb35"
    cpe = "cpe:2.3:a:nginx:nginx:1.25.4:*:*:*:*:*:*:*"
    id = "nginx"
    licenses = ["BSD-2-Clause"]
    name = "Nginx Server"
    purl = "pkg:generic/nginx@1.25.4?checksum=760729901acbaa517996e681ee6ea259032985e37c2768beef80df3a877deed9&download_url=https://nginx.org/download/nginx-1.25.4.tar.gz"
    source = "https://nginx.org/download/nginx-1.25.4.tar.gz"
    source-checksum = "sha256:760729901acbaa517996e681ee6ea259032985e37c2768beef80df3a877deed9"
    stacks = ["Initializ Distroless Stack"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.25.4_linux_x64_bionic_12775fe6.tgz"
    version = "1.25.4"

  [[metadata.dependencies]]
    checksum = "sha256:955da83b7c4ce9f840a5138cd277cc92bbde32205154d1c0c028f2fa3a2579ec"
    cpe = "cpe:2.3:a:nginx:nginx:1.25.5:*:*:*:*:*:*:*"
    id = "nginx"
    licenses = ["BSD-2-Clause"]
    name = "Nginx Server"
    purl = "pkg:generic/nginx@1.25.5?checksum=2fe2294f8af4144e7e842eaea884182a84ee7970e11046ba98194400902bbec0&download_url=https://nginx.org/download/nginx-1.25.5.tar.gz"
    source = "https://nginx.org/download/nginx-1.25.5.tar.gz"
    source-checksum = "sha256:2fe2294f8af4144e7e842eaea884182a84ee7970e11046ba98194400902bbec0"
    stacks = ["Initializ Distroless Stack"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.25.5_linux_x64_bionic_955da83b.tgz"
    version = "1.25.5"

  [[metadata.dependencies]]
    checksum = "sha256:f9c178e360d09eb0016f93b4ba2a0c0db25f447ae39fb250556142d2940cdc3d"
    cpe = "cpe:2.3:a:nginx:nginx:1.26.1:*:*:*:*:*:*:*"
    id = "nginx"
    licenses = ["BSD-2-Clause"]
    name = "Nginx Server"
    purl = "pkg:generic/nginx@1.26.1?checksum=f9187468ff2eb159260bfd53867c25ff8e334726237acf227b9e870e53d3e36b&download_url=https://nginx.org/download/nginx-1.26.1.tar.gz"
    source = "https://nginx.org/download/nginx-1.26.1.tar.gz"
    source-checksum = "sha256:f9187468ff2eb159260bfd53867c25ff8e334726237acf227b9e870e53d3e36b"
    stacks = ["Initializ Distroless Stack"]
    uri = "https://artifacts.paketo.io/nginx/nginx_1.26.1_linux_x64_bionic_f9c178e3.tgz"
    version = "1.26.1"

  [[metadata.dependencies]]
    checksum = "sha256:65bb4477c2a9ff80bd59a30461b70792d318780e9490e1e19476a7630761a67f"
    cpe = "cpe:2.3:a:nginx:nginx:1.26.2:*:*:*:*:*:*:*"
    id = "nginx"
    licenses = ["BSD-2-Clause"]
    name = "Nginx Server"
    purl = "pkg:generic/nginx@1.26.2?checksum=627fe086209bba80a2853a0add9d958d7ebbdffa1a8467a5784c9a6b4f03d738&download_url=https://nginx.org/download/nginx-1.26.2.tar.gz"
    source = "https://nginx.org/download/nginx-1.26.2.tar.gz"
    source-checksum = "sha256:627fe086209bba80a2853a0add9d958d7ebbdffa1a8467a5784c9a6b4f03d738"
    stacks = ["Initializ Distroless Stack"]
    uri = "https://initializ-buildpacks.s3.amazonaws.com/nginx/nginx_1.26.2_linux_x64_bionic_65bb4477.tgz"
    version = "1.26.2"

  [[metadata.dependency-constraints]]
    constraint = "1.25.*"
    id = "nginx"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "1.26.*"
    id = "nginx"
    patches = 2
  [metadata.version-lines]
    mainline = "1.25.*"
    stable = "1.26.*"

[[stacks]]
  id = "Initializ Distroless Stack"
